<?php
/**
 * Страница "Список виджетов".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Список виджетов</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>Список виджетов динамически формируется в соответствии с активным фильтром: отображаются либо установленные, либо не установленные виджеты, либо обе категории.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Название.</b> Название, описание и версия виджета;</li>
        <li><b>Идентификатор.</b> Уникальный идентификатор виджета;</li>
        <li><b>Путь.</b> Локальный путь к установленному модулю;</li>
        <li><b>Автор.</b> Автор виджета;</li>
        <li><b>Версия.</b> Версия виджета;</li>
        <li><b>Назначение.</b> Назначение виджета: Панель управления, Сайт;</li>
        <li><b>Доступность.</b> Доступ к виджету через Панель управления или сайт;</li>
        <li><b>Статус.</b> Статус виджета: установлен, не установлен, ошибка, неизвестно.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Установить.</b> Вызывает форму для установки выбранного виджета из списка;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Удалить.</b> Полностью удаляет установленный виджет;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет пакет загруженного виджета;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-unmount.svg' ?>" /> <b>Демонтаж.</b> Удаляет (деинсталлирует) установленный виджет без удаления его из репозитория;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-download.svg' ?>" /> <b>Скачать.</b> Скачивает пакет виджета, соответствующий элементу, выделенному в списке;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-upload.svg' ?>" /> <b>Загрузить.</b> Загружает файл пакета виджета для дальнейшей установки;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызывает форму для редактирования виджета;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение виджетов в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список виджетов;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-update-config.svg' ?>" /> <b>Обновить.</b> Выполняет обновление конфигурации установленных виджетов. Используется при внесении изменений в файлы конфигурации виджетов или приложения;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о виджете;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает или скрывает столбцы, которые скрыты по умолчанию;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска виджетов в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Выполняет фильтрацию списка виджетов по признаку их установки: отображаются либо установленные, либо не установленные виджеты (в зависимости от выбранного критерия).</li>
    </ul>
</article>