<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Widget manager</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The manager performs: installation, removal and dismantling of web application widgets.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">List of widgets</a></li>
        <li><a href="<?= $url('edit') ?>">Editing a widget</a></li>
        <li><a href="<?= $url('install') ?>">Installing a widget</a></li>
    </ul>
</article>