<?php
/**
 * Страница "Установка виджета".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Installing a widget</h1>
    <p>The form appears after clicking on the <b>"Install"</b> button on the toolbar <a href="<?= $url('grid') ?>">list of widgets</a>.</p>
    <h2>Form tabs</h2>
    <h3>Tab "Information"</h3>
    <p>The tab displays information about the version, purpose of the widget, author, and installation requirements.</p>

    <h3>Tab "Configuration"</h3>
    <p>The tab will display the main configuration parameters of the widget and the choice of installation in the Partitions panel.</p>
</article>